### ISSUE TITLE
Remove white lines in generated standalone headers

### ISSUE THREAD

**Issue by edouarda** [NumScale/scripts#1]
White lines are useless are the code isn't meant to be read and it takes up useless bytes.

**Comment by jfalcou** [comment]
This feature clashes with file containing multi-line macro ended by /**/.
Can we make it optional then cuase I think special casing macro will be difficult

**Comment by ccharly** [comment]
can you give me an example? if it is too hard to handle, then yes we can easily add an option to enable or not empty lines removing...

**Comment by jfalcou** [comment]
#define FOO(X)  \
    X = X+X; \
    X = X*X; \
    /**/
    #define BAR(X)  \
    X = X-X; \
    X = X/X; \
    /**/

gets turned into

    #define FOO(X)  \
    X = X+X; \
    X = X*X; \
    #define BAR(X)  \
    X = X-X; \
    X = X/X; \

wich is not correct as \ will merge both macros.
This is becasue we strip comments THEN we strip empty lines.

If it's doable we should not remove comments if previous line ends with \
